apiVersion: batch/v1
kind: Job
metadata:
  name: prodall3
spec:
  completions: 9
  parallelism: 9
  template:
    metadata:
        annotations:
            container.apparmor.security.beta.kubernetes.io/scraper: unconfined
    spec:
      containers:
      - name: scraper
        resources:
          requests:
            memory: "3000Mi"
            cpu: "0.5"
          limits:
            cpu: "0.8"
        image: gcr.io/t-pulsar-252617/panoscraper:v1
        command: ["/app/DownloadRunnerDockerEntrypoint.sh", "sidewalk-sea.cs.washington.edu",  "antli@128.8.132.187:/fs/jonf-sidewalk/Panoramas/scrapes_dump_seattle", "22"]
        volumeMounts:
          - mountPath: /dev/fuse
            name: dev-fuse
        securityContext:
          privileged: true
      volumes:
      - name: dev-fuse
        hostPath:
          path: /dev/fuse
      restartPolicy: Never
  backoffLimit: 4